# =============================================================================
# StashAI Server - Docker Compose Configuration (Simplified)
# =============================================================================

services:
  # StashAI Server - Main API Gateway
  stash-ai-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: stash-ai-server
    ports:
      - "9998:9998"
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=info
      - QUEUE_DB_PATH=/app/data/queue.db
      - QUEUE_ENABLED=true
      - DIRECT_MODE=false
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - .:/app
    networks:
      - stash-ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9998/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Huey Worker - Background Task Processing
  huey-worker:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: stash-ai-huey-worker
    command: python worker.py
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=info
      - QUEUE_DB_PATH=/app/data/queue.db
      - QUEUE_ENABLED=true
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - .:/app
    networks:
      - stash-ai-network
    restart: unless-stopped

  # Visage Facial Recognition Service
  visage:
    build:
      context: ./Services/visage
      dockerfile: Dockerfile
    container_name: stash-ai-visage
    ports:
      - "9997:8000"  # Map external port 9997 to internal FastAPI port 8000
      - "7860:7860"  # Gradio web interface
    environment:
      - PYTHONPATH=/app
    volumes:
      - visage-models:/app/models
      - visage-data:/app/data
    networks:
      - stash-ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 60s

volumes:
  visage-models:
    driver: local
  visage-data:
    driver: local

networks:
  stash-ai-network:
    driver: bridge